# Generated by Django 4.2.3 on 2023-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_chapters_course2',
            field=models.IntegerField(default=0),
        ),
    ]
