# Generated by Django 4.2.3 on 2023-08-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userprogress_completed_chapters_course3'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_chapters_course4',
            field=models.IntegerField(default=0),
        ),
    ]
